; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp-wrover-kit

[env:esp-wrover-kit]
platform = espressif32@4.0.0
board = esp-wrover-kit
framework = arduino
board_build.f_flash = 40000000L
board_build.flash_mode = qio
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
build_flags = -DBOARD_HAS_PSRAM -mfix-esp32-psram-cache-issue -DLFS_NO_DEBUG
	-D CURRENT_TIME=$UNIX_TIME
	-D ESP_DRD_USE_LITTLEFS=1 
	-D DOUBLERESETDETECTOR_DEBUG=true

monitor_speed = 19200
monitor_rts = 0
monitor_dtr = 0
lib_deps = 
	mathieucarbou/ESPAsyncWebServer@^3.6.0
	khoih-prog/ESP_DoubleResetDetector@^1.3.2
lib_ignore = 
	AsyncTCP_RP2040W
lib_ldf_mode = deep
